### ISSUE TITLE
Build Errors and issues

### ISSUE THREAD

**Issue by JerimiahOfficial** [Khanx/ExtendedAPI#16]
![eoororor](https://user-images.githubusercontent.com/38990407/42662375-609caed0-85ff-11e8-870f-6947a497a9dc.PNG)

Tries to find name spaces for:
NPC
Recipe Storage
Pipliz
IJob
InventoryItem
ItemTypesServer
etc.

**Comment by Khanx** [comment]
You have not added the Colony Survival dll

Check this link:

https://github.com/pipliz/ColonySurvival/wiki/Beginners-Guide-to-Modding

Remember to use ** .Net 3.5**
