### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by CsfDeathDemon** [Khanx/ExtendedAPI#17]
How in the actual F*ck do you install this?  It is literally the only thing you have not added documentation for yet every mod made with this needs it installed for them to work.

**Comment by Khanx** [comment]
Hi,

Basically you have to add the mod to the game (i recomend you to use the CSModManager) and later to add the dll of this mod to your mod (if you use VS add as a reference)

And YES, if you use this mod your mod need that the player have both mods installed yours and this one, in CSModManager you can add dependencies.

**Comment by Khanx** [comment]
Added a tutorial about how to install and use the mod: [https://github.com/Khanx/ExtendedAPI/wiki/%C2%BFHow-to-start%3F](¿How to start?)
